jobs:
- job: DotnetExtensionPackCI
  timeoutInMinutes: 5
  cancelTimeoutInMinutes: 2

  pool:
      vmImage: 'vs2017-win2016'

  steps:
  - task: Npm@1
    displayName: 'Npm install'
    inputs:
      command: 'install'

  - task: CmdLine@2
    displayName: 'Build .NET extension pack'
    inputs:
      script: |
        echo Building .NET extension pack vsix...        
        npx vsce@latest package
  
  - task: CopyFiles@2
    inputs:
      Contents: '*.vsix'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
